name: ASP.NET Core CI

on: 
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1.x
      if: matrix.os == 'macOS-latest' || matrix.os == 'ubuntu-latest'
    - uses: actions/checkout@v1
    - name: Build with dotnet
      run: dotnet build ./IOwe.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./IOwe.sln --configuration Release
